apiVersion: v1
kind: ConfigMap
metadata:
  name: aspect-edge2-operator-config
data:
  edge-config.yml: |
    type: edge
    notification:
      type: pull
      pullPeriod: 30
    logLevel: debug
    registry:
      URL: gitea.corp.ailabs.tw
      protocol: https
      username: aspect_user2
      userToken: 1qaz_WSX
    aggregatorModelRepoName: gitea/aspect_lab3_global
    edgeModelRepoName: gitea/aspect_edge_repo2
    trainPlanRepoName: gitea/aspect_lab3_trainplan